version: 2
jobs:
  build:
    working_directory: ~/lern
    docker:
      - image: 'circleci/node:8-browsers'
      - image: 'circleci/mongo:3.2'
    steps:
      - checkout
      - restore_cache:
          key: meteor
      - run:
          name: 'Install Meteor'
          command: 'meteor || curl https://install.meteor.com | /bin/sh'
      - run:
          name: 'Check Meteor'
          command: 'meteor --version'
      - save_cache:
          key: meteor
          paths:
            - ~/.meteor
      - run:
          name: 'Update npm'
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
      - run:
          name: 'Install npm wee'
          command: 'npm install'
      - save_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run:
          name: 'Mock settings.json'
          command: 'echo { \"credentials\": { \"S3\": { \"accessKeyId\": \"\", \"secretAccessKey\": \"\" } } } > settings.json'
      - run:
          name: 'Check settings.json'
          command: 'cat settings.json'
      - run:
          name: Test
          command: 'npm test'
  deploy:
    working_directory: ~/lern
    docker:
      - image: 'circleci/mongo:3.2'
    steps:
      - checkout
      - run:
          name: 'Check Meteor'
          command: 'meteor --version'
      - run:
          name: Aliasing
          command: 'alias meteor=/usr/local/bin/meteor'
      - run:
          name: ls
          command: ls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
